/**
 * `dnd fixtures --coverage`: which entities of the base package are exercised
 * by at least one character fixture. Writes fixtures/coverage.md.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { parse } from "yaml";

import { loadPackages } from "@byloth/dnd-platform-engine";
import type { Character } from "@byloth/dnd-platform-engine";

import { toPackageSource } from "../io/to-package-source.js";

const TYPES = ["class", "subclass", "species", "background", "feat", "condition", "item", "spell"] as const;
/** Entity types that must reach 100 %. */
export const GATED = new Set<string>(["class", "subclass", "species", "background", "feat", "condition"]);

export interface CoverageBucket
{
    readonly total: number;
    readonly covered: number;
    readonly missing: readonly string[];
}
export interface CoverageReport
{
    readonly byType: Readonly<Record<string, CoverageBucket>>;
    readonly ok: boolean;
}

const ENTITY_ID = /^[a-z0-9.-]+\.(class|subclass|species|background|feat|condition|item|spell)\.[a-z0-9.-]+$/;

function referencedIds(character: Character): Set<string>
{
    const ids = new Set<string>();
    const visit = (node: unknown): void =>
    {
        if (typeof node === "string" && ENTITY_ID.test(node)) { ids.add(node); }
        else if (Array.isArray(node)) { node.forEach(visit); }
        else if (node && typeof node === "object") { Object.values(node).forEach(visit); }
    };
    visit(character);

    return ids;
}

export function computeCoverage(root: string, fixturesDir: string, basePackageDir: string): CoverageReport
{
    const set = loadPackages([toPackageSource(basePackageDir)]);
    const used = new Set<string>();
    for (const name of readdirSync(fixturesDir).sort())
    {
        const path = join(fixturesDir, name, "character.yaml");
        if (!existsSync(path)) { continue; }
        for (const id of referencedIds(parse(readFileSync(path, "utf8")) as Character)) { used.add(id); }
    }
    const byType: Record<string, { total: number, covered: number, missing: string[] }> = {};
    for (const type of TYPES) { byType[type] = { total: 0, covered: 0, missing: [] }; }
    for (const entity of set.entities.values())
    {
        const bucket = byType[entity.type];
        if (bucket === undefined) { continue; }
        bucket.total += 1;
        if (used.has(entity.id)) { bucket.covered += 1; }
        else { bucket.missing.push(entity.id); }
    }
    const ok = TYPES.every((type) => !GATED.has(type) || byType[type]!.covered === byType[type]!.total);
    void root;

    return { byType: byType, ok: ok };
}

export function writeCoverageReport(report: CoverageReport, path: string): void
{
    const lines = ["# Fixture coverage of the base package", "", "Generated by `dnd fixtures --coverage`. Gated types must reach 100 %.", "",
        "| Type | Covered | Total | % | Gated |", "|---|---|---|---|---|"];
    for (const [type, b] of Object.entries(report.byType))
    {
        const pct = b.total === 0 ? 100 : Math.round((b.covered / b.total) * 100);
        lines.push(`| ${type} | ${b.covered} | ${b.total} | ${pct} | ${GATED.has(type) ? "yes" : "no"} |`);
    }
    for (const [type, b] of Object.entries(report.byType))
    {
        if (b.missing.length === 0 || !GATED.has(type)) { continue; }
        lines.push("", `## Missing ${type}`, "", ...b.missing.map((id) => `- \`${id}\``));
    }
    const spells = report.byType["spell"];
    if (spells && spells.missing.length)
    {
        lines.push("", `## Spells not known by any fixture (${spells.missing.length})`, "", spells.missing.map((id) => `\`${id.split(".").pop()}\``).join(", "));
    }
    writeFileSync(resolve(path), `${lines.join("\n")}\n`);
}
