/**
 * The icons the interface uses, by name: inline SVG from Font Awesome's solid set, imported one by one so only
 * these reach the bundle (no webfont, no stylesheet). A name missing here renders nothing; add it when used.
 */

import {
    faArrowUpRightFromSquare,
    faBeerMugEmpty,
    faBolt,
    faBoxArchive,
    faBookOpen,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faCircle,
    faCircleCheck,
    faCircleXmark,
    faDice,
    faDiceD20,
    faDragon,
    faFeather,
    faFileArrowUp,
    faGlobe,
    faHandFist,
    faHardDrive,
    faHeart,
    faHeartCrack,
    faLightbulb,
    faLinkSlash,
    faLock,
    faMagnifyingGlass,
    faMinus,
    faPlus,
    faRotateLeft,
    faShieldHalved,
    faSliders,
    faSpinner,
    faStar,
    faThumbtack,
    faTrash,
    faTriangleExclamation,
    faUsers,
    faWandSparkles,
    faXmark
} from "@fortawesome/free-solid-svg-icons";
import type { IconDefinition } from "@fortawesome/free-solid-svg-icons";

const _icons: readonly IconDefinition[] = [
    faArrowUpRightFromSquare,
    faBeerMugEmpty,
    faBolt,
    faBoxArchive,
    faBookOpen,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faCircle,
    faCircleCheck,
    faCircleXmark,
    faDice,
    faDiceD20,
    faDragon,
    faFeather,
    faFileArrowUp,
    faGlobe,
    faHandFist,
    faHardDrive,
    faHeart,
    faHeartCrack,
    faLightbulb,
    faLinkSlash,
    faLock,
    faMagnifyingGlass,
    faMinus,
    faPlus,
    faRotateLeft,
    faShieldHalved,
    faSliders,
    faSpinner,
    faStar,
    faThumbtack,
    faTrash,
    faTriangleExclamation,
    faUsers,
    faWandSparkles,
    faXmark
];

export const ICONS: Readonly<Record<string, IconDefinition>> =
    Object.fromEntries(_icons.map((icon) => [icon.iconName, icon]));
