/**
 * Generate `src/generated/types.ts` (TypeScript types) and
 * `src/generated/schemas.ts` (the schemas as constants) from `schemas/*.json`.
 *
 *   node packages/schema/scripts/generate.ts [--check]
 *
 * With --check the files are generated into memory and compared with the
 * committed ones; a difference fails the command (used in CI).
 */

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { compile } from "json-schema-to-typescript";
import type { JSONSchema4 } from "json-schema";

const PACKAGE_DIR = resolve(import.meta.dirname, "..");
const SCHEMAS_DIR = resolve(PACKAGE_DIR, "schemas");
const OUT_DIR = resolve(PACKAGE_DIR, "src", "generated");
const CHECK = process.argv.includes("--check");
const BANNER = "/* eslint-disable */\n// Generated by scripts/generate.ts from schemas/*.schema.json. Do not edit.\n";

const names = readdirSync(SCHEMAS_DIR)
    .filter((file) => file.endsWith(".schema.json"))
    .map((file) => file.replace(/\.schema\.json$/, ""))
    .sort();

function pascal(name: string): string
{
    return name.replace(/(^|-)([a-z0-9])/g, (_match, _sep, char: string) => char.toUpperCase());
}

// ---- schemas.ts --------------------------------------------------------------

const schemas = Object.fromEntries(names.map((name) =>
{
    const source = readFileSync(resolve(SCHEMAS_DIR, `${name}.schema.json`), "utf8");

    return [name, JSON.parse(source) as unknown];
}));
const schemasTs = `${BANNER}\nexport const SCHEMAS = ${JSON.stringify(schemas, null, 4)} as const;\n\n` +
    "export type SchemaName = keyof typeof SCHEMAS;\n";

// ---- types.ts ------------------------------------------------------------------

// One synthetic root referencing every schema, so shared definitions are declared once.
const root: JSONSchema4 = {
    $id: "https://dnd-platform.byloth.dev/schema/v0/root.schema.json",
    title: "Root",
    type: "object",
    additionalProperties: false,
    properties: Object.fromEntries(names.map((name) => [pascal(name), { $ref: `${name}.schema.json` }]))
};
const typesTs = await compile(root, "Root", {
    cwd: SCHEMAS_DIR,
    bannerComment: BANNER,
    additionalProperties: false,
    declareExternallyReferenced: true,
    strictIndexSignatures: true,
    style: { singleQuote: false, semi: true, tabWidth: 4, printWidth: 120 }
});

// ---- write or check ------------------------------------------------------------

const outputs: [string, string][] = [["schemas.ts", schemasTs], ["types.ts", typesTs]];
if (CHECK)
{
    const stale = outputs.filter(([file, content]) =>
    {
        try
        {
            return readFileSync(resolve(OUT_DIR, file), "utf8") !== content;
        }
        catch
        {
            return true;
        }
    });
    if (stale.length)
    {
        const list = stale.map(([file]) => file).join(", ");
        console.error(`generated files out of date: ${list}; run pnpm generate:types`);
        process.exitCode = 1;
    }
    else { console.log("generated files are up to date"); }
}
else
{
    mkdirSync(OUT_DIR, { recursive: true });
    for (const [file, content] of outputs) { writeFileSync(resolve(OUT_DIR, file), content); }
    console.log(`generated ${outputs.map(([file]) => file).join(", ")} from ${names.length} schemas`);
}
