/** Writing of generated package files with a stable layout. */

import { cpSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, resolve } from "node:path";

import { stringify } from "yaml";

import { REPO_ROOT } from "./lib.ts";

/**
 * `IMPORT_OUT=<dir>` writes the two packages into `<dir>/srd51` and `<dir>/srd51-creatures` instead, copied
 * there first with their hand-written files: a preview that several people (or agents) can build at once.
 */
const OUT = process.env["IMPORT_OUT"] ? resolve(process.env["IMPORT_OUT"]) : undefined;
const SOURCE_DIRS = ["srd51", "srd51-creatures"].map((id) => resolve(REPO_ROOT, "packages/content", id));
if (OUT)
{
    for (const dir of SOURCE_DIRS) { cpSync(dir, resolve(OUT, basename(dir)), { recursive: true }); }
}
export const CONTENT_DIR = OUT ? resolve(OUT, "srd51") : SOURCE_DIRS[0]!;
/** The SRD's creatures, a package of their own so the character sheet does not download them. */
export const CREATURES_DIR = OUT ? resolve(OUT, "srd51-creatures") : SOURCE_DIRS[1]!;
export const GENERATED_HEADER = "# Generated by tools/import (map stage) from the SRD 5.1 datasets pinned in tools/import/sources.lock.yaml.\n" +
    "# Mechanics come from tools/import/overlay/<entity-id>.yaml; edit those, then re-run `node tools/import/src/map.ts`.\n";

export const GENERATED_DIRS = [
    "classes", "subclasses", "species", "backgrounds", "feats", "spells", "spell-lists", "items", "conditions", "rules", "tables"
];

export function cleanGenerated(): void
{
    for (const dir of GENERATED_DIRS) { rmSync(resolve(CONTENT_DIR, dir), { recursive: true, force: true }); }
    rmSync(resolve(CREATURES_DIR, "creatures"), { recursive: true, force: true });
}

export function emit(relativePath: string, entity: Record<string, unknown>, base = CONTENT_DIR): void
{
    const path = resolve(base, relativePath);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, `${GENERATED_HEADER}${stringify(entity, { lineWidth: 0, blockQuote: "literal" })}`);
}

export function text(en: string | null | undefined): { en: string } | undefined
{
    const cleaned = (en ?? "").replace(/\r\n/g, "\n").trim();

    return cleaned ? { en: cleaned } : undefined;
}

export function slug(value: string): string
{
    return value
        .toLowerCase()
        .replace(/[’']/g, "")
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "");
}
