/** Writing of generated package files with a stable layout. */

import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import { stringify } from "yaml";

import { REPO_ROOT } from "./lib.ts";

export const CONTENT_DIR = resolve(REPO_ROOT, "packages/content/srd51");
export const GENERATED_HEADER = "# Generated by tools/import (map stage) from the SRD 5.1 datasets pinned in tools/import/sources.lock.yaml.\n" +
    "# Mechanics come from tools/import/overlay/<entity-id>.yaml; edit those, then re-run `node tools/import/src/map.ts`.\n";

export const GENERATED_DIRS = [
    "classes", "subclasses", "species", "backgrounds", "feats", "spells", "spell-lists", "items", "conditions", "rules", "tables"
];

export function cleanGenerated(): void
{
    for (const dir of GENERATED_DIRS) { rmSync(resolve(CONTENT_DIR, dir), { recursive: true, force: true }); }
}

export function emit(relativePath: string, entity: Record<string, unknown>): void
{
    const path = resolve(CONTENT_DIR, relativePath);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, `${GENERATED_HEADER}${stringify(entity, { lineWidth: 0, blockQuote: "literal" })}`);
}

export function text(en: string | null | undefined): { en: string } | undefined
{
    const cleaned = (en ?? "").replace(/\r\n/g, "\n").trim();

    return cleaned ? { en: cleaned } : undefined;
}

export function slug(value: string): string
{
    return value
        .toLowerCase()
        .replace(/[’']/g, "")
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "");
}
