/**
 * Generate the SRD 5.1 inventory (docs/phase-0/inventory/) from the cached
 * upstream datasets, plus the classification skeletons that the effect
 * catalogue is checked against.
 *
 *   node tools/import/src/inventory.ts
 */

import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { stringify } from "yaml";

import { REPO_ROOT, readCachedJson } from "./lib.ts";
import * as o5e from "./open5e.ts";

const OUT = resolve(REPO_ROOT, "docs/phase-0/inventory");
const WORK = resolve(REPO_ROOT, "tools/import/work/classification");
mkdirSync(OUT, { recursive: true });
mkdirSync(WORK, { recursive: true });

const HEADER = "<!-- Generated by tools/import/src/inventory.ts from the datasets pinned in tools/import/sources.lock.yaml. Do not edit. -->\n\n";

function write(name: string, body: string): void
{
    writeFileSync(resolve(OUT, name), `${HEADER}${body.trimEnd()}\n`);
}
function md(text: string | null | undefined): string
{
    return (text ?? "").replace(/\r\n/g, "\n").trim();
}
function cell(text: string | null | undefined): string
{
    return md(text).replace(/\|/g, "\\|")
        .replace(/\n+/g, " ");
}
function by<T>(items: T[], key: (item: T) => string): Map<string, T[]>
{
    const map = new Map<string, T[]>();
    for (const item of items)
    {
        const k = key(item);
        map.set(k, [...(map.get(k) ?? []), item]);
    }

    return map;
}
function count<T>(items: T[], key: (item: T) => string): [string, number][]
{
    return [...by(items, key).entries()]
        .map(([k, v]) => [k, v.length] as [string, number])
        .sort((a, b) => a[0].localeCompare(b[0]));
}

// ---- 5e-database (counts and structured tables) ----------------------------

const DB = "src/2014/en/5e-SRD-";
function db<T>(name: string): T[] { return readCachedJson<T[]>("5e-database", `${DB}${name}.json`); }
interface DbLevel
{
    level: number;
    prof_bonus: number;
    class: { index: string };
    subclass?: { index: string };
    class_specific?: Record<string, unknown>;
    spellcasting?: Record<string, number>;
}
interface DbMagicItem
{
    index: string;
    name: string;
    rarity: { name: string };
    variant: boolean;
    variants: unknown[];
    desc: string[];
    equipment_category: { index: string };
}
const dbCounts: Record<string, number> = {};
for (const file of readdirSync(resolve(REPO_ROOT, "tools/import/cache/5e-database/src/2014/en")))
{
    const name = file.replace(/^5e-SRD-|\.json$/g, "");
    dbCounts[name] = db<unknown>(name).length;
}
const dbLevels = db<DbLevel>("Levels");
const dbMagic = db<DbMagicItem>("Magic-Items");

// ---- Open5e (primary) ------------------------------------------------------

const classes = o5e.rows<o5e.CharacterClass>("CharacterClass");
const features = o5e.rows<o5e.ClassFeature>("ClassFeature");
const featureItems = o5e.rows<o5e.ClassFeatureItem>("ClassFeatureItem");
const species = o5e.rows<o5e.Species>("Species");
const traits = o5e.rows<o5e.SpeciesTrait>("SpeciesTrait");
const backgrounds = o5e.rows<o5e.Background>("Background");
const backgroundBenefits = o5e.rows<o5e.BackgroundBenefit>("BackgroundBenefit");
const feats = o5e.rows<o5e.Feat>("Feat");
const featBenefits = o5e.rows<o5e.FeatBenefit>("FeatBenefit");
const spells = o5e.rows<o5e.Spell>("Spell");
const spellOptions = o5e.rows<o5e.SpellCastingOption>("SpellCastingOption");
const items = o5e.rows<o5e.Item>("Item");
const magicItems = o5e.rows<o5e.Item>("MagicItem");
const weapons = o5e.rows<o5e.Weapon>("Weapon");
const weaponProps = o5e.rows<o5e.WeaponPropertyAssignment>("WeaponPropertyAssignment");
const armors = o5e.rows<o5e.Armor>("Armor");
const conditions = o5e.rows<o5e.ConditionDescription>("ConditionDescription");
const rules = o5e.rows<o5e.Rule>("Rule");
const ruleSets = o5e.rows<o5e.RuleSet>("RuleSet");

const baseClasses = classes
    .filter((c) => c.fields.subclass_of === null)
    .sort((a, b) => a.fields.name.localeCompare(b.fields.name));
const subclasses = classes.filter((c) => c.fields.subclass_of !== null);
const itemsByFeature = by(featureItems, (i) => i.fields.parent);
const featuresByOwner = by(features, (f) => f.fields.parent);
const traitsByOwner = by(traits, (t) => t.fields.parent);
const optionsBySpell = by(spellOptions, (s) => s.fields.parent);
const propsByWeapon = by(weaponProps, (p) => p.fields.weapon);
const weaponByPk = new Map(weapons.map((w) => [String(w.pk), w.fields]));
const armorByPk = new Map(armors.map((a) => [String(a.pk), a.fields]));

function featureLevel(pk: string | number): number | null
{
    const levels = (itemsByFeature.get(String(pk)) ?? []).map((i) => i.fields.level);

    return levels.length ? Math.min(...levels) : null;
}
function featureTable(pk: string | number): string
{
    const rowsWithValue = (itemsByFeature.get(String(pk)) ?? [])
        .filter((i) => i.fields.column_value !== null || i.fields.detail !== null)
        .sort((a, b) => a.fields.level - b.fields.level);
    if (!rowsWithValue.length) { return ""; }

    return `  Table: ${rowsWithValue.map((i) => `${i.fields.level} → ${i.fields.column_value ?? i.fields.detail}`).join("; ")}\n`;
}

// ---- 00-summary --------------------------------------------------------------

{
    const lines: string[] = ["# SRD 5.1 inventory — summary", "",
        "Counts from the two upstream datasets pinned in `tools/import/sources.lock.yaml`. Open5e is the primary source of the inventory; 5e-database is the cross-check and the source of the structured level tables.", "",
        "| Entity | Open5e (srd-2014) | 5e-database (2014) | Note |", "|---|---|---|---|",
        `| Classes | ${baseClasses.length} | ${dbCounts["Classes"]} | |`,
        `| Subclasses | ${subclasses.length} | ${dbCounts["Subclasses"]} | one per class in the SRD |`,
        `| Class and subclass features | ${features.length} | ${dbCounts["Features"]} | 5e-database splits choice features (fighting styles, expertise picks) into separate records |`,
        `| Feature level rows | ${featureItems.length} | ${dbLevels.length} level records | Open5e: one row per feature per level; 5e-database: one record per class per level with \`class_specific\` counters |`,
        `| Species (races) | ${species.filter((s) => s.fields.subspecies_of === null).length} | ${dbCounts["Races"]} | |`,
        `| Subspecies (subraces) | ${species.filter((s) => s.fields.subspecies_of !== null).length} | ${dbCounts["Subraces"]} | |`,
        `| Species traits | ${traits.length} | ${dbCounts["Traits"]} | Open5e repeats a trait per species; 5e-database shares traits across species |`,
        `| Backgrounds | ${backgrounds.length} | ${dbCounts["Backgrounds"]} | Acolyte only |`,
        `| Background benefits | ${backgroundBenefits.length} | — | |`,
        `| Feats | ${feats.length} | ${dbCounts["Feats"]} | Grappler only |`,
        `| Feat benefits | ${featBenefits.length} | — | |`,
        `| Spells | ${spells.length} | ${dbCounts["Spells"]} | |`,
        `| Spell casting options (upcast/ritual rows) | ${spellOptions.length} | — | |`,
        `| Mundane items | ${items.length} | ${dbCounts["Equipment"]} | |`,
        `| Weapons / armour | ${weapons.length} / ${armors.length} | — | |`,
        `| Magic items | ${magicItems.length} | ${dbCounts["Magic-Items"]} (${dbMagic.filter((m) => !m.variant).length} non-variant) | Open5e expands variants (e.g. one entry per armour type); 5e-database keeps a base entry with variants |`,
        `| Conditions | ${conditions.length} | ${dbCounts["Conditions"]} | |`,
        `| Rule sets / rules | ${ruleSets.length} / ${rules.length} | ${dbCounts["Rules"]} / ${dbCounts["Rule-Sections"]} | |`,
        "", "## Spells by level", "", "| Level | Count |", "|---|---|",
        ...count(spells, (s) => String(s.fields.level)).map(([k, n]) => `| ${k} | ${n} |`),
        "", "## Spells by school", "", "| School | Count |", "|---|---|",
        ...count(spells, (s) => s.fields.school).map(([k, n]) => `| ${k} | ${n} |`),
        "", "## Spells with structured fields (Open5e)", "",
        `- attack roll: ${spells.filter((s) => s.fields.attack_roll).length}`,
        `- saving throw: ${spells.filter((s) => s.fields.saving_throw_ability).length}`,
        `- damage roll: ${spells.filter((s) => s.fields.damage_roll).length}`,
        `- concentration: ${spells.filter((s) => s.fields.concentration).length}`,
        `- ritual: ${spells.filter((s) => s.fields.ritual).length}`,
        `- area shape: ${spells.filter((s) => s.fields.shape_type).length}`,
        "", "## Items by category", "", "| Category | Count |", "|---|---|",
        ...count(items, (i) => i.fields.category).map(([k, n]) => `| ${k} | ${n} |`),
        "", "## Magic items by rarity (Open5e)", "", "| Rarity | Count |", "|---|---|",
        ...count(magicItems, (i) => i.fields.rarity ?? "?").map(([k, n]) => `| ${k} | ${n} |`),
        "", "## Rule sets", "", ...ruleSets.map((r) => `- ${r.fields.name} (${(by(rules, (x) => x.fields.ruleset).get(String(r.pk)) ?? []).length} rules)`)
    ];
    write("00-summary.md", lines.join("\n"));
}

// ---- classes / subclasses ----------------------------------------------------

function classSection(c: { pk: string | number, fields: o5e.CharacterClass }): string[]
{
    const id = o5e.slug(c.pk);
    const lines: string[] = [`## ${c.fields.name} (\`${id}\`)`, ""];
    if (c.fields.subclass_of === null)
    {
        lines.push(`- Hit die: ${c.fields.hit_dice}; saving throws: ${c.fields.saving_throws.join(", ")}; caster type: ${c.fields.caster_type ?? "none"}`);
        const levels = dbLevels.filter((l) => l.class.index === id && !l.subclass).sort((a, b) => a.level - b.level);
        const specific = levels.find((l) => l.class_specific)?.class_specific ?? {};
        const columns = Object.keys(specific);
        if (columns.length)
        {
            lines.push("", "### Level table (5e-database `class_specific`)", "", `| Level | Prof | ${columns.join(" | ")} |`, `|---|---|${columns.map(() => "---").join("|")}|`);
            for (const l of levels)
            {
                lines.push(`| ${l.level} | +${l.prof_bonus} | ${columns.map((k) => JSON.stringify(l.class_specific?.[k] ?? "")).join(" | ")} |`);
            }
        }
        const slots = levels.find((l) => l.spellcasting)?.spellcasting;
        if (slots)
        {
            const keys = Object.keys(slots);
            lines.push("", "### Spellcasting table (5e-database)", "", `| Level | ${keys.join(" | ")} |`, `|---|${keys.map(() => "---").join("|")}|`);
            for (const l of levels) { lines.push(`| ${l.level} | ${keys.map((k) => l.spellcasting?.[k] ?? "").join(" | ")} |`); }
        }
    }
    else
    {
        lines.push(`- Subclass of \`${o5e.slug(c.fields.subclass_of)}\``);
    }
    const own = (featuresByOwner.get(String(c.pk)) ?? [])
        .map((f) => ({ f: f, level: featureLevel(f.pk) }))
        .sort((a, b) => (a.level ?? 99) - (b.level ?? 99) || a.f.fields.name.localeCompare(b.f.fields.name));
    lines.push("", `### Features (${own.length})`, "");
    for (const { f, level } of own)
    {
        lines.push(`#### ${f.fields.name} — level ${level ?? "?"} (\`${o5e.slug(f.pk)}\`)`, "", featureTable(f.pk), md(f.fields.desc), "");
    }

    return lines;
}
write("classes.md", ["# Classes", "", ...baseClasses.flatMap(classSection)].join("\n"));
write("subclasses.md", ["# Subclasses", "", ...subclasses.sort((a, b) => a.fields.name.localeCompare(b.fields.name)).flatMap(classSection)].join("\n"));

// ---- species -----------------------------------------------------------------

{
    const lines: string[] = ["# Species (races) and subspecies", ""];
    for (const s of species.sort((a, b) => a.fields.name.localeCompare(b.fields.name)))
    {
        lines.push(`## ${s.fields.name} (\`${o5e.slug(s.pk)}\`)${s.fields.subspecies_of ? ` — subspecies of \`${o5e.slug(s.fields.subspecies_of)}\`` : ""}`, "", md(s.fields.desc), "");
        for (const t of traitsByOwner.get(String(s.pk)) ?? [])
        {
            lines.push(`### ${t.fields.name} (\`${o5e.slug(t.pk)}\`)`, "", md(t.fields.desc), "");
        }
    }
    write("species.md", lines.join("\n"));
}

// ---- backgrounds, feats, conditions, rules -----------------------------------

const backgroundLines = backgrounds.flatMap((b) => [
    `## ${b.fields.name} (\`${o5e.slug(b.pk)}\`)`, "", md(b.fields.desc), "",
    ...backgroundBenefits
        .filter((x) => x.fields.parent === b.pk)
        .flatMap((x) => [`### ${x.fields.name} (type: ${x.fields.type})`, "", md(x.fields.desc), ""])
]);
write("backgrounds.md", ["# Backgrounds", "", ...backgroundLines].join("\n"));

const featLines = feats.flatMap((f) => [
    `## ${f.fields.name} (\`${o5e.slug(f.pk)}\`)`, "", `Prerequisite: ${f.fields.prerequisite ?? "none"}`, "", md(f.fields.desc), "",
    ...featBenefits
        .filter((x) => x.fields.parent === f.pk)
        .flatMap((x, i) => [`### Benefit ${i + 1}`, "", md(x.fields.desc), ""])
]);
write("feats.md", ["# Feats", "", ...featLines].join("\n"));
const conditionLines = conditions.flatMap((c) => [`## ${c.fields.describes}`, "", md(c.fields.desc), ""]);
write("conditions.md", ["# Conditions", "", ...conditionLines].join("\n"));

const rulesByRuleSet = by(rules, (r) => r.fields.ruleset);
const ruleLines = ruleSets
    .sort((a, b) => a.fields.name.localeCompare(b.fields.name))
    .flatMap((rs) =>
    {
        const own = (rulesByRuleSet.get(String(rs.pk)) ?? []).sort((a, b) => a.fields.index - b.fields.index);
        const bullets = own.map((r) => `- ${r.fields.name} (\`${o5e.slug(r.pk)}\`, ${md(r.fields.desc).length} chars)`);

        return [`## ${rs.fields.name} (\`${o5e.slug(rs.pk)}\`)`, "", ...bullets, ""];
    });
write("rules.md", ["# Rules", "", "Reference text available for the assistant and the cheat sheet (`Rule` entities).", "", ...ruleLines].join("\n"));

// ---- spells ------------------------------------------------------------------

{
    const lines: string[] = ["# Spells", "", "Metadata from Open5e; casting options list the upcast and ritual rows available upstream.", ""];
    for (const [level, group] of [...by(spells, (s) => String(s.fields.level)).entries()].sort())
    {
        lines.push(`## Level ${level} (${group.length})`, "");
        for (const s of group.sort((a, b) => a.fields.name.localeCompare(b.fields.name)))
        {
            const f = s.fields;
            const comps = [f.verbal && "V", f.somatic && "S", f.material && `M${f.material_specified ? ` (${f.material_specified})` : ""}`].filter(Boolean).join(", ");
            const opts = (optionsBySpell.get(String(s.pk)) ?? []).map((x) => x.fields.type).filter((t) => t !== "default");
            lines.push(`### ${f.name} (\`${o5e.slug(s.pk)}\`)`, "",
                `- ${f.school}; casting time: ${f.casting_time}${f.reaction_condition ? ` (${f.reaction_condition})` : ""}; range: ${f.range_text}; duration: ${f.duration}${f.concentration ? " (concentration)" : ""}${f.ritual ? "; ritual" : ""}`,
                `- components: ${comps}; classes: ${f.classes.map(o5e.slug).join(", ")}`,
                `- structured: attack=${f.attack_roll}, save=${f.saving_throw_ability ?? "-"}, damage=${f.damage_roll ?? "-"} ${f.damage_types.join("/")}, shape=${f.shape_type ?? "-"}${f.shape_size ? ` ${f.shape_size}` : ""}, targets=${f.target_type ?? "-"}${f.target_count ? ` ×${f.target_count}` : ""}; options: ${opts.length ? opts.join(", ") : "none"}`,
                "", md(f.desc), ...(md(f.higher_level) ? ["", `*At higher levels.* ${md(f.higher_level)}`] : []), "");
        }
    }
    write("spells.md", lines.join("\n"));
}

// ---- items -------------------------------------------------------------------

{
    const lines: string[] = ["# Items", "", "## Weapons", "", "| Name | Simple | Damage | Range | Properties |", "|---|---|---|---|---|"];
    for (const w of weapons.sort((a, b) => a.fields.name.localeCompare(b.fields.name)))
    {
        const props = (propsByWeapon.get(String(w.pk)) ?? []).map((p) => `${o5e.slug(p.fields.property)}${p.fields.detail ? ` (${p.fields.detail})` : ""}`).join(", ");
        lines.push(`| ${w.fields.name} | ${w.fields.is_simple} | ${w.fields.damage_dice} ${w.fields.damage_type} | ${w.fields.range}/${w.fields.long_range} | ${props} |`);
    }
    lines.push("", "## Armour", "", "| Name | Base AC | + DEX | DEX cap | Stealth disadvantage | STR required |", "|---|---|---|---|---|---|");
    for (const a of armors.sort((x, y) => x.fields.name.localeCompare(y.fields.name)))
    {
        lines.push(`| ${a.fields.name} | ${a.fields.ac_base} | ${a.fields.ac_add_dexmod} | ${a.fields.ac_cap_dexmod ?? "-"} | ${a.fields.grants_stealth_disadvantage} | ${a.fields.strength_score_required ?? "-"} |`);
    }
    lines.push("", "## Mundane items by category", "");
    for (const [cat, group] of [...by(items, (i) => i.fields.category).entries()].sort())
    {
        lines.push(`### ${cat} (${group.length})`, "", "| Name | Cost | Weight | Description |", "|---|---|---|---|");
        for (const i of group.sort((a, b) => a.fields.name.localeCompare(b.fields.name)))
        {
            lines.push(`| ${i.fields.name} | ${i.fields.cost ?? "-"} | ${i.fields.weight ?? "-"} | ${cell(i.fields.desc).slice(0, 200)} |`);
        }
        lines.push("");
    }
    lines.push("## Magic items (5e-database base entries, variants collapsed)", "", "| Name | Category | Rarity | Variants | Description |", "|---|---|---|---|---|");
    for (const m of dbMagic.filter((x) => !x.variant).sort((a, b) => a.name.localeCompare(b.name)))
    {
        lines.push(`| ${m.name} | ${m.equipment_category.index} | ${m.rarity.name} | ${m.variants.length} | ${cell(m.desc.join(" ")).slice(0, 300)} |`);
    }
    write("items.md", lines.join("\n"));
    void weaponByPk;
    void armorByPk;
}

// ---- classification skeletons ------------------------------------------------

interface FeatureRecord
{
    id: string;
    owner: string;
    ownerType: "class" | "subclass" | "species" | "subspecies" | "background" | "feat";
    level: number | null;
    name: string;
    table?: string;
    text: string;
    mechanics: null;
}
const records: FeatureRecord[] = [];
for (const c of classes)
{
    const kind = c.fields.subclass_of === null ? "class" : "subclass";
    for (const f of featuresByOwner.get(String(c.pk)) ?? [])
    {
        const table = featureTable(f.pk).replace(/^\s*Table: /, "")
            .trim();
        records.push({
            id: `srd51.feature.${o5e.slug(c.pk)}.${o5e.slug(f.pk).replace(`${o5e.slug(c.pk)}_`, "")}`,
            owner: o5e.slug(c.pk),
            ownerType: kind,
            level: featureLevel(f.pk),
            name: f.fields.name,
            ...(table ? { table } : {}),
            text: md(f.fields.desc),
            mechanics: null
        });
    }
}
for (const s of species)
{
    const kind = s.fields.subspecies_of === null ? "species" : "subspecies";
    for (const t of traitsByOwner.get(String(s.pk)) ?? [])
    {
        records.push({
            id: `srd51.feature.${o5e.slug(s.pk)}.${o5e.slug(t.pk).replace(`${o5e.slug(s.pk)}_`, "")}`,
            owner: o5e.slug(s.pk),
            ownerType: kind,
            level: null,
            name: t.fields.name,
            text: md(t.fields.desc),
            mechanics: null
        });
    }
}
for (const b of backgroundBenefits)
{
    records.push({
        id: `srd51.feature.${o5e.slug(b.fields.parent)}.${o5e.slug(b.pk).replace(`${o5e.slug(b.fields.parent)}_`, "")}`,
        owner: o5e.slug(b.fields.parent),
        ownerType: "background",
        level: null,
        name: `${b.fields.name} (${b.fields.type})`,
        text: md(b.fields.desc),
        mechanics: null
    });
}
for (const f of feats)
{
    const benefits = featBenefits.filter((x) => x.fields.parent === f.pk).map((x) => `- ${md(x.fields.desc)}`)
        .join("\n");
    records.push({
        id: `srd51.feature.feat.${o5e.slug(f.pk)}`,
        owner: o5e.slug(f.pk),
        ownerType: "feat",
        level: null,
        name: f.fields.name,
        text: `Prerequisite: ${f.fields.prerequisite ?? "none"}\n${md(f.fields.desc)}\n${benefits}`,
        mechanics: null
    });
}
writeFileSync(resolve(OUT, "features.yaml"), "# Classification skeleton: one record per feature, trait or benefit. Generated; " +
`the classified copy is classification.yaml.\n${stringify({ records }, { lineWidth: 0 })}`);

const spellRecords = spells
    .sort((a, b) => a.fields.level - b.fields.level || a.fields.name.localeCompare(b.fields.name))
    .map((s) => ({
        id: `srd51.spell.${o5e.slug(s.pk)}`,
        name: s.fields.name,
        level: s.fields.level,
        school: s.fields.school,
        castingTime: s.fields.casting_time,
        duration: s.fields.duration,
        concentration: s.fields.concentration,
        ritual: s.fields.ritual,
        attack: s.fields.attack_roll,
        save: s.fields.saving_throw_ability,
        damage: s.fields.damage_roll,
        shape: s.fields.shape_type,
        text: md(s.fields.desc),
        higherLevel: md(s.fields.higher_level) || null,
        mechanics: null
    }));
writeFileSync(resolve(OUT, "spells-classification.yaml"), `# Classification skeleton for spells (reduced vocabulary). Generated.\n${stringify({ records: spellRecords }, { lineWidth: 0 })}`);

const magicRecords = dbMagic.filter((m) => !m.variant).sort((a, b) => a.name.localeCompare(b.name))
    .map((m) => ({
        id: `srd51.item.${m.index}`,
        name: m.name,
        category: m.equipment_category.index,
        rarity: m.rarity.name,
        variants: m.variants.length,
        text: m.desc.join("\n"),
        mechanics: null
    }));
writeFileSync(resolve(OUT, "magic-items-classification.yaml"), `# Classification skeleton for magic items (reduced vocabulary). Generated.\n${stringify({ records: magicRecords }, { lineWidth: 0 })}`);

// ---- work partitions for the classification agents ---------------------------

const PARTS: Record<string, (r: FeatureRecord) => boolean> = {
    "part-1-classes-a-d": (r) => ["barbarian", "path-of-the-berserker", "bard", "college-of-lore", "cleric", "life-domain", "druid", "circle-of-the-land"].includes(r.owner),
    "part-2-classes-f-r": (r) => ["fighter", "champion", "monk", "way-of-the-open-hand", "paladin", "oath-of-devotion", "ranger", "hunter"].includes(r.owner),
    "part-3-classes-r-w": (r) => ["rogue", "thief", "sorcerer", "draconic-bloodline", "warlock", "the-fiend", "wizard", "school-of-evocation"].includes(r.owner),
    "part-4-species-bg-feat": (r) => ["species", "subspecies", "background", "feat"].includes(r.ownerType)
};
let assigned = 0;
for (const [name, filter] of Object.entries(PARTS))
{
    const part = records.filter(filter);
    assigned += part.length;
    writeFileSync(resolve(WORK, `${name}.yaml`), stringify({ records: part }, { lineWidth: 0 }));
}
if (assigned !== records.length) { throw new Error(`partition mismatch: ${assigned} of ${records.length} feature records assigned`); }
writeFileSync(resolve(WORK, "part-5-spells-0-2.yaml"), stringify({ records: spellRecords.filter((s) => s.level <= 2) }, { lineWidth: 0 }));
writeFileSync(resolve(WORK, "part-6-spells-3-9.yaml"), stringify({ records: spellRecords.filter((s) => s.level >= 3) }, { lineWidth: 0 }));
writeFileSync(resolve(WORK, "part-7-magic-items.yaml"), stringify({ records: magicRecords }, { lineWidth: 0 }));

console.log(`features: ${records.length} (${count(records, (r) => r.ownerType).map(([k, n]) => `${k} ${n}`)
    .join(", ")})`);
console.log(`spells: ${spellRecords.length}; magic items: ${magicRecords.length}`);
console.log(`written to ${OUT} and ${WORK}`);
