/**
 * Merge the classified partitions produced by the classification agents into
 * docs/phase-0/inventory/classification*.yaml and summarise them.
 *
 *   node tools/import/src/merge-classification.ts
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { parse, stringify } from "yaml";

import { REPO_ROOT } from "./lib.ts";

const INVENTORY = resolve(REPO_ROOT, "docs/phase-0/inventory");
const WORK = resolve(REPO_ROOT, "tools/import/work/classification");

const FEATURE_KINDS = new Set([
    "modify", "grant-proficiency", "declare-resource", "add-action", "grant-spellcasting", "grant-spells",
    "extend-spell-list", "roll-advantage", "roll-disadvantage", "defense", "add-text", "add-section",
    "open-choice", "define-table", "text-only", "play-mode"
]);
const SPELL_KINDS = new Set([
    "damage", "attack", "save", "healing", "buff-modify", "condition", "summon", "utility-text", "scaling"
]);
const ITEM_KINDS = new Set([
    "text-only", "modify", "add-action", "grant-spells", "defense", "roll-advantage", "roll-disadvantage",
    "charges", "attunement", "play-mode"
]);
const CONFIDENCE = new Set(["high", "medium", "low"]);

interface Skeleton { id: string, name: string, [key: string]: unknown }
interface Classified
{
    id: string;
    mechanics: string[];
    targets?: string[];
    resource?: string;
    activation?: string;
    confidence: string;
    note?: string;
}
interface Group { skeleton: string, parts: string[], kinds: Set<string>, output: string, title: string }

const GROUPS: Group[] = [
    {
        skeleton: "features.yaml",
        output: "classification.yaml",
        title: "Features, traits and benefits",
        kinds: FEATURE_KINDS,
        parts: ["part-1-classes-a-d", "part-2-classes-f-r", "part-3-classes-r-w", "part-4-species-bg-feat"]
    },
    {
        skeleton: "spells-classification.yaml",
        output: "spells-classified.yaml",
        title: "Spells",
        kinds: SPELL_KINDS,
        parts: ["part-5-spells-0-2", "part-6-spells-3-9"]
    },
    {
        skeleton: "magic-items-classification.yaml",
        output: "magic-items-classified.yaml",
        title: "Magic items",
        kinds: ITEM_KINDS,
        parts: ["part-7-magic-items"]
    }
];

const errors: string[] = [];
const summary: string[] = ["# Classification summary", "",
    "Generated by `tools/import/src/merge-classification.ts` from the agents' partitions.",
    "Human review: see README.md in this directory.", ""];

function loadRecords<T>(path: string): T[]
{
    return (parse(readFileSync(path, "utf8")) as { records: T[] }).records;
}

function tally(values: string[]): [string, number][]
{
    const counts = new Map<string, number>();
    for (const v of values) { counts.set(v, (counts.get(v) ?? 0) + 1); }

    return [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
}

for (const group of GROUPS)
{
    const skeleton = loadRecords<Skeleton>(resolve(INVENTORY, group.skeleton));
    const byId = new Map(skeleton.map((r) => [r.id, r]));
    const classified: Classified[] = [];

    for (const part of group.parts)
    {
        const path = resolve(WORK, `${part}.classified.yaml`);
        if (!existsSync(path))
        {
            errors.push(`${group.title}: missing ${part}.classified.yaml`);

            continue;
        }
        for (const record of loadRecords<Classified>(path))
        {
            if (!byId.has(record.id)) { errors.push(`${part}: unknown id ${record.id}`); }
            if (!Array.isArray(record.mechanics) || record.mechanics.length === 0)
            {
                errors.push(`${part}: ${record.id} has no mechanics`);
            }
            if (!CONFIDENCE.has(record.confidence))
            {
                errors.push(`${part}: ${record.id} has confidence "${record.confidence}"`);
            }
            for (const m of record.mechanics ?? [])
            {
                const ok = group.kinds.has(m) ||
                    m.startsWith("needs-new-kind:") ||
                    m.startsWith("condition-key-needed:");
                if (!ok) { errors.push(`${part}: ${record.id} uses "${m}", not in the vocabulary`); }
            }
            classified.push(record);
        }
    }

    const seen = new Set(classified.map((r) => r.id));
    for (const r of skeleton)
    {
        if (!seen.has(r.id)) { errors.push(`${group.title}: ${r.id} not classified`); }
    }
    if (seen.size !== classified.length) { errors.push(`${group.title}: duplicate ids in the partitions`); }

    // Merged file: skeleton fields + classification, in skeleton order.
    const merged = skeleton.map((r) =>
    {
        const c = classified.find((x) => x.id === r.id);
        const { mechanics: _skip, ...rest } = r;
        void _skip;

        return { ...rest, ...(c ?? { mechanics: null, confidence: "missing" }) };
    });
    writeFileSync(resolve(INVENTORY, group.output), `# ${group.title}: classification against effect catalogue v0. ` +
    "Merged by tools/import/src/merge-classification.ts; " +
    "the *.classified.yaml partitions are the agents' raw output.\n" +
    stringify({ records: merged }, { lineWidth: 0 }));

    const mechanics = classified.flatMap((r) => r.mechanics);
    const name = (id: string) => byId.get(id)?.name ?? id;
    summary.push(`## ${group.title} (${classified.length} of ${skeleton.length})`, "",
        "### Mechanics by frequency", "", "| value | records |", "|---|---|",
        ...tally(mechanics.map((m) => m.split(":")[0] ?? m)).map(([k, n]) => `| \`${k}\` | ${n} |`), "");

    const newKinds = classified.filter((r) => r.mechanics.some((m) => m.startsWith("needs-new-kind:")));
    if (newKinds.length)
    {
        summary.push("### `needs-new-kind` proposals", "");
        const byProposal = new Map<string, Classified[]>();
        for (const r of newKinds)
        {
            for (const m of r.mechanics.filter((x) => x.startsWith("needs-new-kind:")))
            {
                const key = m.slice("needs-new-kind:".length).trim();
                byProposal.set(key, [...(byProposal.get(key) ?? []), r]);
            }
        }
        for (const [key, rs] of [...byProposal.entries()].sort((a, b) => b[1].length - a[1].length))
        {
            const bullets = rs.map((r) => `  - \`${r.id}\` ${name(r.id)}${r.note ? ` — ${r.note}` : ""}`);
            summary.push(`- **${key}** (${rs.length}):`, ...bullets);
        }
        summary.push("");
    }
    const condKeys = classified.filter((r) => r.mechanics.some((m) => m.startsWith("condition-key-needed:")));
    if (condKeys.length)
    {
        summary.push("### `condition-key-needed`", "",
            ...tally(condKeys.flatMap((r) => r.mechanics
                .filter((m) => m.startsWith("condition-key-needed:"))
                .map((m) => m.slice(21).trim())))
                .map(([k, n]) => `- **${k}** (${n}): ${condKeys
                    .filter((r) => r.mechanics.some((m) => m.endsWith(k)))
                    .map((r) => `\`${r.id}\``)
                    .join(", ")}`), "");
    }
    const low = classified.filter((r) => r.confidence === "low");
    const lowBullets = low.map((r) => `- \`${r.id}\` ${name(r.id)}: [${r.mechanics.join(", ")}]${r.note ? ` — ${r.note}` : ""}`);
    summary.push(`### Low confidence (${low.length})`, "", ...lowBullets, "");
    const textOnly = classified
        .filter((r) => r.mechanics.length === 1)
        .filter((r) => r.mechanics[0] === "text-only" || r.mechanics[0] === "utility-text");
    summary.push(`### Text-only (${textOnly.length})`, "", textOnly.map((r) => `\`${r.id}\``).join(", "), "");
}

writeFileSync(resolve(INVENTORY, "classification.md"), `${summary.join("\n").trimEnd()}\n`);

if (errors.length)
{
    console.error(`merge finished with ${errors.length} problem(s):`);
    for (const e of errors) { console.error(`- ${e}`); }
    process.exitCode = 1;
}
else
{
    console.log(`merged ${GROUPS.map((g) => g.output).join(", ")}; summary in classification.md`);
}
void readdirSync;
